# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codemob < Formula
  desc "AI agent workspace manager — parallel isolated sessions via git worktrees"
  homepage "https://github.com/codemob-ai/codemob"
  version "1.2.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.6/codemob_1.2.6_darwin_amd64.tar.gz"
      sha256 "5f62a8fff5ca856d65f39f1577af052d8da4c44cd97c13de75b08fa581e958cb"

      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.6/codemob_1.2.6_darwin_arm64.tar.gz"
      sha256 "5aa7dac0034b37cefa2b92cf176036086aabde10fa685fdc9c2fc6c627875c87"

      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.6/codemob_1.2.6_linux_amd64.tar.gz"
      sha256 "649dbe8c4598fedb9f9a17162a5d0fc0e766f40744860b894b323f534170fcb4"
      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.6/codemob_1.2.6_linux_arm64.tar.gz"
      sha256 "1fb74e116f402a65b49641538e735b3952c0a8d1cce172f31c6c73a97c795cc7"
      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
  end

  def caveats
    <<~EOS
      To complete setup, run:
        codemob init

      This configures shell integration (mob alias, claude/codex wrappers).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/codemob --version")
  end
end
