# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codemob < Formula
  desc "AI agent workspace manager — parallel isolated sessions via git worktrees"
  homepage "https://github.com/codemob-ai/codemob"
  version "1.2.4"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.4/codemob_1.2.4_darwin_amd64.tar.gz"
      sha256 "01cbfedfe4bca4eeddaa7adb5f1859144b6faeba83358f9a13feda80deba619c"

      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.4/codemob_1.2.4_darwin_arm64.tar.gz"
      sha256 "386e0f941d4d6bedf8266150c7877c188f051a911832fc090f6ec9621b030abc"

      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.4/codemob_1.2.4_linux_amd64.tar.gz"
      sha256 "4c139d24a0df3ee8bca00f40ff24b5ea9a9d2b478a48f832888d204ec5159aba"
      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.4/codemob_1.2.4_linux_arm64.tar.gz"
      sha256 "45788a9912a4e581797da464726f285e984ced7f6d6a21d7cafb24871b13ee99"
      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
  end

  def caveats
    <<~EOS
      To complete setup, run:
        codemob init

      This configures shell integration (mob alias, claude/codex wrappers).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/codemob --version")
  end
end
