# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codemob < Formula
  desc "AI agent workspace manager — parallel isolated sessions via git worktrees"
  homepage "https://github.com/codemob-ai/codemob"
  version "1.2.1"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.1/codemob_1.2.1_darwin_amd64.tar.gz"
      sha256 "19ad831d97449dddad519f030dcff492810419254c86a09aa4c04ee2317d7b84"

      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.1/codemob_1.2.1_darwin_arm64.tar.gz"
      sha256 "44de7dbc73ce58f5e2e2815a0d92453aef05278a3a1069611e7949ee00f571ff"

      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.1/codemob_1.2.1_linux_amd64.tar.gz"
      sha256 "950e75f7907d84cc1e35fd1e928c7b0c1dbbf097884bc74132bc3258c14028eb"
      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codemob-ai/codemob/releases/download/v1.2.1/codemob_1.2.1_linux_arm64.tar.gz"
      sha256 "5f419ca6bd44bf7546ec68c2ac76a00e7a85f7d9f613f1c0220f824f4e7588da"
      define_method(:install) do
        bin.install "codemob"
        (share/"codemob").install "codemob-shell.sh"
      end
    end
  end

  def caveats
    <<~EOS
      To complete setup, run:
        codemob init

      This configures shell integration (mob alias, claude/codex wrappers).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/codemob --version")
  end
end
